# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from urllib.request import urlopen
from urllib.parse import urlencode, unquote, quote_plus
import urllib
import json
import pandas as pd
import requests
from bs4 import BeautifulSoup 
from PySide2.QtWidgets import QMessageBox
import redis
import json
import sys


r = redis.StrictRedis(host='127.0.0.1', port=6379, db=0)

student_info = {
    "name": "양종호",
    "num":"2014920025",
    "grade":"4",
    "semester":"2",
    "college":"공과대학",
    "major":"컴퓨터과학부"

}
student_basket=[["71065","01","클라우드컴퓨팅","현철승","월06,07,08/19-112/113","48","3"],
                ["71077","01","컴퓨터과학종합설계","유하진","목01,02,03,04/19-112/113","65","3"],
                ["71021","01","컴퓨터통신","안상현","목07,08,09/19-110/111","75","3"]]
    
index=["과목번호","분반","과목명","교수명","요일","수강정원","학점"]
"""
# set
json_test_dict = json.dumps(student_info, ensure_ascii=False).encode('utf-8')
r.set("student_info", json_test_dict)
# get
json_test_dict = r.get('student_info').decode('utf-8')
test_dict2 = dict(json.loads(json_test_dict))
"""

for key,value in student_info.items():
    r.hmset("student_info",{key:value})

basket_index=0
basket_id="장바구니"+str(basket_index)
for i in student_basket:
    for id in range(len(index)):
        r.hmset(basket_id,{index[id]:i[id]})
    basket_index=basket_index+1
    basket_id="장바구니"+str(basket_index)



print(r.hget('student_info','name').decode('utf-8'))




class Ui_MainWindow(QtCore.QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 688)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #인적사항 프레임
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 18, 91, 81))
        self.frame.setStyleSheet("background-color: rgb(144, 187, 200);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(31)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 56, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 58, 71, 41))
        self.label_3.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(1)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 18, 71, 41))
        self.label_4.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(190, 18, 123, 41))
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 58, 123, 41))
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(312, 18, 72, 41))
        self.label_7.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setLineWidth(1)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(312, 58, 72, 41))
        self.label_8.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_8.setFrameShape(QtWidgets.QFrame.Box)
        self.label_8.setLineWidth(1)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(383, 58, 126, 41))
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(383, 18, 126, 41))
        self.label_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")

        #학점프레임
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(557, 19, 61, 20))
        self.label_11.setStyleSheet("background-color: rgb(144, 187, 200);")
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(557, 38, 61, 21))
        self.label_12.setStyleSheet("background-color: rgb(144, 187, 200);")
        self.label_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(557, 58, 61, 20))
        self.label_13.setStyleSheet("background-color: rgb(144, 187, 200);")
        self.label_13.setFrameShape(QtWidgets.QFrame.Box)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(557, 77, 61, 21))
        self.label_14.setStyleSheet("background-color: rgb(144, 187, 200);")
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(617, 19, 61, 20))
        self.label_15.setStyleSheet("")
        self.label_15.setFrameShape(QtWidgets.QFrame.Box)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")

        apply_list=[]
        self.max_credit=0
        apply_len=r.scard('2014920025_apply')
        for i in r.smembers('2014920025_apply'):
            apply_id="2014920025_"+i.decode('utf-8')
            self.max_credit=self.max_credit+int(r.hget(apply_id,"학점").decode('utf-8'))
            

        self.label17=14-self.max_credit
        if self.label17<0:
                self.label17=0
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setText(str(self.max_credit))
        self.label_16.setGeometry(QtCore.QRect(617, 77, 61, 21))
        self.label_16.setStyleSheet("")
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setText(str(self.label17))
        self.label_17.setGeometry(QtCore.QRect(617, 58, 61, 20))
        self.label_17.setStyleSheet("")
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")




        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(617, 38, 61, 21))
        self.label_18.setStyleSheet("")
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")

        #탭화면
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 141, 651, 291))
        self.tabWidget.setObjectName("tabWidget")
        #탭1(장바구니)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        
        #장바구니 테이블
        self.tableWidget4 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget4.setGeometry(QtCore.QRect(10, 10, 621, 251))
        self.tableWidget4.setStyleSheet("")
        self.tableWidget4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget4.setShowGrid(True)
        self.tableWidget4.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget4.setObjectName("tableWidget4")
        self.tableWidget4.setColumnCount(8)

        item = QtWidgets.QTableWidgetItem("과목번호")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget4.setHorizontalHeaderItem(0, item)
        self.tableWidget4.setColumnWidth(0,51)
        item = QtWidgets.QTableWidgetItem("분반")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget4.setHorizontalHeaderItem(1, item)
        self.tableWidget4.setColumnWidth(1,30)
        item = QtWidgets.QTableWidgetItem("교과목명")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget4.setHorizontalHeaderItem(2, item)
        self.tableWidget4.setColumnWidth(2,131)
        item = QtWidgets.QTableWidgetItem("강사명")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget4.setHorizontalHeaderItem(3, item)
        self.tableWidget4.setColumnWidth(3,51)
        item = QtWidgets.QTableWidgetItem("요일 및 강의실")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget4.setHorizontalHeaderItem(4, item)
        self.tableWidget4.setColumnWidth(4,191)
        item = QtWidgets.QTableWidgetItem("전체\n인원")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget4.setHorizontalHeaderItem(5, item)
        self.tableWidget4.setColumnWidth(5,57)
        item = QtWidgets.QTableWidgetItem("수강\n인원")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget4.setHorizontalHeaderItem(6, item)
        self.tableWidget4.setColumnWidth(6,57)
        item = QtWidgets.QTableWidgetItem("신청")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget4.setHorizontalHeaderItem(7, item)
        self.tableWidget4.setColumnWidth(7,51)

        basket_list=[]
        tmp=[]
        for i in range(len(student_basket)):
            basket_id="장바구니"+str(i)
            for j in r.hvals(basket_id):
                tmp.append(j.decode('utf-8'))
            basket_list.append(tmp)
            tmp=[]

        self.tableWidget4.setRowCount(len(student_basket))
        item_widget=[]
        for i in range(len(student_basket)):
            item_widget.append(0)
            for j in range(6):
                item=QtWidgets.QTableWidgetItem(basket_list[i][j])
                self.tableWidget4.setItem(i,j,item)
            
            item=QtWidgets.QTableWidgetItem()
            self.tableWidget4.setItem(i,6,item)

            item_widget[i] = QtWidgets.QPushButton("신청")
            
            self.tableWidget4.setCellWidget(i, 7, item_widget[i])
            item_widget[i].clicked.connect(self.submitmethod(basket_list[i]))

         #헤더 사이즈 조절
        header = self.tableWidget4.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(6, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(7, QtWidgets.QHeaderView.Stretch)
        

        #tab_2의 테이블화면
        
        
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.tableWidget2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget2.setGeometry(QtCore.QRect(10, 50, 621, 211))
        self.tableWidget2.setStyleSheet("")
        self.tableWidget2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget2.setShowGrid(True)
        self.tableWidget2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setColumnCount(8)

        item = QtWidgets.QTableWidgetItem("과목번호")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget2.setHorizontalHeaderItem(0, item)
        self.tableWidget2.setColumnWidth(0,51)
        item = QtWidgets.QTableWidgetItem("분반")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget2.setHorizontalHeaderItem(1, item)
        self.tableWidget2.setColumnWidth(1,30)
        item = QtWidgets.QTableWidgetItem("교과목명")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget2.setHorizontalHeaderItem(2, item)
        self.tableWidget2.setColumnWidth(2,131)
        item = QtWidgets.QTableWidgetItem("강사명")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget2.setHorizontalHeaderItem(3, item)
        self.tableWidget2.setColumnWidth(3,51)
        item = QtWidgets.QTableWidgetItem("요일 및 강의실")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget2.setHorizontalHeaderItem(4, item)
        self.tableWidget2.setColumnWidth(4,191)
        item = QtWidgets.QTableWidgetItem("전체\n인원")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget2.setHorizontalHeaderItem(5, item)
        self.tableWidget2.setColumnWidth(5,57)
        item = QtWidgets.QTableWidgetItem("수강\n인원")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget2.setHorizontalHeaderItem(6, item)
        self.tableWidget2.setColumnWidth(6,57)
        item = QtWidgets.QTableWidgetItem("신청")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget2.setHorizontalHeaderItem(7, item)
        self.tableWidget2.setColumnWidth(7,51)
       
        #과목검색의 프레임
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 621, 48))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_35 = QtWidgets.QLabel(self.frame_2)
        self.label_35.setGeometry(QtCore.QRect(0, 0, 77, 24))
        self.label_35.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_35.setFrameShape(QtWidgets.QFrame.Box)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.textEdit = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit.setGeometry(QtCore.QRect(77, 0, 82, 24))
        self.textEdit.setObjectName("textEdit")
        self.label_36 = QtWidgets.QLabel(self.frame_2)
        self.label_36.setGeometry(QtCore.QRect(0, 23, 131, 24))
        self.label_36.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_36.setFrameShape(QtWidgets.QFrame.Box)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_2.setGeometry(QtCore.QRect(131, 23, 131, 24))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_37 = QtWidgets.QLabel(self.frame_2)
        self.label_37.setGeometry(QtCore.QRect(327, 0, 51, 24))
        self.label_37.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_37.setFrameShape(QtWidgets.QFrame.Box)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame_2)
        self.label_38.setGeometry(QtCore.QRect(480, 0, 51, 24))
        self.label_38.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_38.setFrameShape(QtWidgets.QFrame.Box)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setGeometry(QtCore.QRect(530, 0, 41, 24))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(4)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.clicked.connect(self.clickMethod)
        self.pushButton.setGeometry(QtCore.QRect(569, 0, 50, 41))
        self.pushButton.setStyleSheet("background-color:rgb(213,213,213);\n"
"border-width: 1px;\n"
"border-color: black;")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.label_50 = QtWidgets.QLabel(self.frame_2)
        self.label_50.setGeometry(QtCore.QRect(159, 0, 59, 24))
        self.label_50.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.label_50.setFrameShape(QtWidgets.QFrame.Box)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(217, 0, 110, 24))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.currentIndexChanged.connect(self.comboBoxFunction)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_2.setGeometry(QtCore.QRect(379, 0, 101, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(40, 450, 131, 21))
        self.label_39.setObjectName("label_39")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 443, 6, 29))
        self.line.setStyleSheet("background-color: rgb(144, 187, 200);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        

        #수강신청내역의 테이블
        self.tableWidget3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget3.setGeometry(QtCore.QRect(42, 470, 621, 211))
        self.tableWidget3.setStyleSheet("")
        self.tableWidget3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget3.setShowGrid(True)
        self.tableWidget3.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget3.setObjectName("tableWidget3")
        self.tableWidget3.setColumnCount(8)

        item = QtWidgets.QTableWidgetItem("과목번호")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget3.setHorizontalHeaderItem(0, item)
        self.tableWidget3.setColumnWidth(0,51)
        item = QtWidgets.QTableWidgetItem("분반")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget3.setHorizontalHeaderItem(1, item)
        self.tableWidget3.setColumnWidth(1,30)
        item = QtWidgets.QTableWidgetItem("교과목명")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget3.setHorizontalHeaderItem(2, item)
        self.tableWidget3.setColumnWidth(2,131)
        item = QtWidgets.QTableWidgetItem("강사명")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget3.setHorizontalHeaderItem(3, item)
        self.tableWidget3.setColumnWidth(3,51)
        item = QtWidgets.QTableWidgetItem("요일 및 강의실")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget3.setHorizontalHeaderItem(4, item)
        self.tableWidget3.setColumnWidth(4,191)
        item = QtWidgets.QTableWidgetItem("전체\n인원")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget3.setHorizontalHeaderItem(5, item)
        self.tableWidget3.setColumnWidth(5,57)
        item = QtWidgets.QTableWidgetItem("수강\n인원")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget3.setHorizontalHeaderItem(6, item)
        self.tableWidget3.setColumnWidth(6,57)
        item = QtWidgets.QTableWidgetItem("삭제")
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget3.setHorizontalHeaderItem(7, item)
        self.tableWidget3.setColumnWidth(7,51)

        apply_list=[]
        tmp=[]
        apply_len=r.scard('2014920025_apply')
        for i in r.smembers('2014920025_apply'):
            apply_id="2014920025_"+i.decode('utf-8')
            for j in r.hvals(apply_id):
                tmp.append(j.decode('utf-8'))
            apply_list.append(tmp)
            tmp=[]
      
        self.tableWidget3.setRowCount(apply_len)
        item_widget=[]
        for i in range(apply_len):
            item_widget.append(0)
            for j in range(6):
                item=QtWidgets.QTableWidgetItem(apply_list[i][j])
                self.tableWidget3.setItem(i,j,item)
            
            item=QtWidgets.QTableWidgetItem()
            self.tableWidget3.setItem(i,6,item)

            item_widget[i] = QtWidgets.QPushButton("삭제")
            
            self.tableWidget3.setCellWidget(i, 7, item_widget[i])
            item_widget[i].clicked.connect(self.deletemethod)

         #헤더 사이즈 조절
        header = self.tableWidget3.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(6, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(7, QtWidgets.QHeaderView.Stretch)


        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 111, 6, 29))
        self.line_2.setStyleSheet("background-color: rgb(144, 187, 200);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(40, 117, 131, 21))
        self.label_48.setObjectName("label_48")

        #시간표 테이블
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(700, 40, 324, 501))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(10)

    
        day=['월','화','수','목','금']
        apply_len=r.scard('2014920025_apply')
        for i in r.smembers('2014920025_apply'):
            apply_id="2014920025_"+i.decode('utf-8')
            parsing=r.hget(apply_id,"요일").decode('utf-8')
            if parsing==' ':
                continue
            parsing=parsing.split('/')[0]
            table_column=day.index(parsing[0])
            table_row=parsing[1:].split(',')
            print(int(table_row[0])-1,table_column)
            for i in table_row:
                self.tableWidget.setItem(int(i)-1, table_column, QtWidgets.QTableWidgetItem())
                self.tableWidget.item(int(i)-1,table_column).setBackground(QtGui.QColor(225, 225, 225))
            


        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setVerticalHeaderItem(9, item)
        item.setBackground(QtGui.QColor(225, 225, 225))
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setHorizontalHeaderItem(0, item)

        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(225, 225, 225))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(34)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(47)
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(510, 120, 181, 16))
        self.label_49.setObjectName("label_49")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    #신청버튼이 눌렸을때
    def submitmethod(self,submit):
        def real():
            if r.exists("2014920025_"+submit[2])==1:
                msgBox = QMessageBox()
                msgBox.setWindowTitle("alert")
                msgBox.setText("중복신청입니다.")
                msgBox.setStandardButtons(QMessageBox.Yes)
                msgBox.exec_()
                return 

            day=['월','화','수','목','금']
            
            apply_id="2014920025_"+submit[2]
            parsing=submit[4]
            print(parsing)
            if parsing!=' ':
                parsing=parsing.split('/')[0]
                table_column=day.index(parsing[0])
                table_row=parsing[1:].split(',')
                print(int(table_row[0])-1,table_column)
                for i in table_row:
                    if self.tableWidget.item(int(i)-1,table_column)==None:
                        continue
                    else:
                        msgBox = QMessageBox()
                        msgBox.setWindowTitle("alert")
                        msgBox.setText("시간표중복입니다.")
                        msgBox.setStandardButtons(QMessageBox.Yes)
                        msgBox.exec_()
                        return 
                for i in table_row:
                    self.tableWidget.setItem(int(i)-1, table_column, QtWidgets.QTableWidgetItem())
                    self.tableWidget.item(int(i)-1,table_column).setBackground(QtGui.QColor(225, 225, 225))


            self.max_credit=self.max_credit+int(submit[6])
            self.label_16.setText(str(self.max_credit))
            self.label17=14-self.max_credit
            if self.label17<0:
                self.label17=0
            self.label_17.setText(str(self.label17))

            item_widget=[]
            r.sadd("2014920025_apply",submit[2])
            self.tableWidget3.setRowCount(self.tableWidget3.rowCount()+1)
            for i in range(self.tableWidget3.rowCount()):
                item_widget.append(0)
            apply_id="2014920025_"+submit[2]
            for i in range(7):
                r.hmset(apply_id,{index[i]:submit[i]})
                item=QtWidgets.QTableWidgetItem(submit[i])
                self.tableWidget3.setItem(self.tableWidget3.rowCount()-1,i,item)
            item=QtWidgets.QTableWidgetItem()
            self.tableWidget3.setItem(self.tableWidget3.rowCount()-1,6,item)
            item_widget[self.tableWidget3.rowCount()-1] = QtWidgets.QPushButton("삭제")
            self.tableWidget3.setCellWidget(self.tableWidget3.rowCount()-1, 7, item_widget[self.tableWidget3.rowCount()-1])
            item_widget[self.tableWidget3.rowCount()-1].clicked.connect(self.deletemethod)
        return real
        #print(submitlist)
    #삭제버튼을 눌렀을때
    @QtCore.pyqtSlot()
    def deletemethod(self):
        btn=self.sender()
        row = self.tableWidget3.indexAt(btn.pos()).row()
        r.srem('2014920025_apply',self.tableWidget3.item(row,2).text())
        self.max_credit=self.max_credit-int(r.hget("2014920025_"+self.tableWidget3.item(row,2).text(),"학점"))
        self.label_16.setText(str(self.max_credit))
        self.label17=14-self.max_credit
        if self.label17<0:
                self.label17=0
        self.label_17.setText(str(self.label17))

        day=['월','화','수','목','금']
        parsing=r.hget("2014920025_"+self.tableWidget3.item(row,2).text(),"요일").decode('utf-8')
        print(parsing)
        if parsing!=' ':
           parsing=parsing.split('/')[0]
           table_column=day.index(parsing[0])
           table_row=parsing[1:].split(',')
           print(int(table_row[0])-1,table_column)
           for i in table_row:
               self.tableWidget.takeItem(int(i)-1, table_column)
              
        

        print(self.tableWidget3.item(row,2).text())
        apply_id="2014920025_"+self.tableWidget3.item(row,2).text()
        r.delete(apply_id)
        #r.lindex("student_apply",self.tableWidget3.item(row,2).text())
        self.tableWidget3.removeRow(row)
            
    #과목검색 버튼이 눌렸을때
    def clickMethod(self):
        params=''
        combolist=['A201120212','A201130213','A200110111','A200220122','A200280128','A200370137']
        combo_2list=[['A201140214','A201150215','A201160216'],['A201190219'],['A200130113','A200180118','A200200120'],['A200230123','A200230123','A200250125'],['A200310131','A200300130','A200320132'],['A200480148','A200490149','A200500150']]
        if self.comboBox_2.currentText()=='':
            msgBox = QMessageBox()
            msgBox.setWindowTitle("alert")
            msgBox.setText("필수항목을 선택하세요")
            msgBox.setStandardButtons(QMessageBox.Yes)
            msgBox.exec_()
        else:
            params=params+'&dept='+combolist[self.comboBox.currentIndex()]
            params=params+'&subDept='+combo_2list[self.comboBox.currentIndex()][self.comboBox_2.currentIndex()]

            if self.textEdit.toPlainText()!='':
                params=params+'&subjectNo='+self.textEdit.toPlainText()
            if self.textEdit_2.toPlainText()!='':
                params=params+'&subjectNm='+self.textEdit_2.toPlainText()
        url='https://wise.uos.ac.kr/uosdoc/api.ApiUcrMjTimeInq.oapi?'
        apiKey='202006623GWT62609'
        year='2020'
        term='A10'
        deptDiv='20000'
        queryParams='apiKey='+apiKey+'&year='+year+'&term='+term+'&deptDiv='+deptDiv+params
        print(queryParams)
        url=url+queryParams
        req=requests.get(url)
        html=req.text
        soup=BeautifulSoup(req.content,'html.parser')

        subnum_list=[] #과목번호
        subcl_list=[] #분반
        subname_list=[] #과목명
        subpro_list=[] #교수명
        classnm_list=[] #강의실
        limit_list=[] #수강정원
        credit_list=[]
        shyr_list=[]

        datas=soup.find_all('subject_nm')
        for data in datas:
            subname_list.append(data.text)
        datas=soup.find_all('subject_no')
        for data in datas:
            subnum_list.append(data.text)
        datas=soup.find_all('class_div')
        for data in datas:
            subcl_list.append(data.text)
        datas=soup.find_all('prof_nm')
        for data in datas:
            subpro_list.append(data.text)
        datas=soup.find_all('class_nm')
        for data in datas:
            classnm_list.append(data.text)
        datas=soup.find_all('tlsn_limit_count')
        for data in datas:
            limit_list.append(data.text)
        datas=soup.find_all('credit')
        for data in datas:
            credit_list.append(data.text)
        datas=soup.find_all('shyr')
        for data in datas:
            shyr_list.append(data.text)

        print(type(self.spinBox.value()))
        i=0
        while(True):
            if i==len(shyr_list):
                break
            if shyr_list[i]!=str(self.spinBox.value()):
                del subnum_list[i]
                del subcl_list[i]
                del subname_list[i]
                del subpro_list[i]
                del classnm_list[i]
                del limit_list[i]
                del credit_list[i]
                del shyr_list[i]
                continue
            i=i+1

        alllist=[subnum_list]+[subcl_list]+[subname_list]+[subpro_list]+[classnm_list]+[limit_list]+[credit_list]+[shyr_list]
        
        num=len(subnum_list)
        self.tableWidget2.setRowCount(num)
        search_index=[]
        for i in range(num):
            search_index.append(0)
            tmp_list=[]
            for j in range(6):
                item=QtWidgets.QTableWidgetItem(alllist[j][i])
                tmp_list.append(alllist[j][i])
                
                self.tableWidget2.setItem(i,j,item)
            tmp_list.append(alllist[6][i])
            item=QtWidgets.QTableWidgetItem()
            self.tableWidget2.setItem(i,6,item)

            search_index[i] = QtWidgets.QPushButton("신청")
            self.tableWidget2.setCellWidget(i, 7, search_index[i])
            search_index[i].clicked.connect(self.submitmethod(tmp_list))

        #헤더 사이즈 조절
        header = self.tableWidget2.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(6, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(7, QtWidgets.QHeaderView.Stretch)
        #self.tableWidget2.horizontalHeader().setSectionResizeMode(1)


    def comboBoxFunction(self):
        index=[['행정학과','국제관계학과','경제학부'],['경영학부'],['화학공학과','신소재공학과','컴퓨터과학부'],['영어영문학과','국어국문학과','국사학과'],['수학과','통계학과','물리학과'],['건축학부','도시공학과','교통공학과']]
        self.comboBox_2.clear()
        for item in index[self.comboBox.currentIndex()]:
            self.comboBox_2.addItem(item)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "2020년 2학기"))
        self.label_2.setText(_translate("MainWindow", r.hget('student_info','grade').decode('utf-8')+"학년-"+r.hget('student_info','semester').decode('utf-8')))
        self.label_3.setText(_translate("MainWindow", "이름"))
        self.label_4.setText(_translate("MainWindow", "학번"))
        self.label_5.setText(_translate("MainWindow", r.hget('student_info','num').decode('utf-8')))
        self.label_6.setText(_translate("MainWindow", r.hget('student_info','name').decode('utf-8')))
        self.label_7.setText(_translate("MainWindow", "단과대"))
        self.label_8.setText(_translate("MainWindow", "학과"))
        self.label_9.setText(_translate("MainWindow", r.hget('student_info','major').decode('utf-8')))
        self.label_10.setText(_translate("MainWindow", r.hget('student_info','college').decode('utf-8')))
        self.label_11.setText(_translate("MainWindow", "최대학점"))
        self.label_12.setText(_translate("MainWindow", "최소학점"))
        self.label_13.setText(_translate("MainWindow", "필요학점"))
        self.label_14.setText(_translate("MainWindow", "현재학점"))
        self.label_15.setText(_translate("MainWindow", "23"))
        """
        self.label_16.setText(_translate("MainWindow", "8"))      
        self.label_17.setText(_translate("MainWindow", "6"))
        """
        self.label_18.setText(_translate("MainWindow", "14"))
        
        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "장바구니"))

      

        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p>과목번호</p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p>교과목명</p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p>*학과</p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>학년</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "검색"))
        self.label_50.setText(_translate("MainWindow", "*소속대학"))
        self.comboBox.setItemText(0, _translate("MainWindow", "정경대학"))
        self.comboBox.setItemText(1, _translate("MainWindow", "경영대학"))
        self.comboBox.setItemText(2, _translate("MainWindow", "공과대"))
        self.comboBox.setItemText(3, _translate("MainWindow", "인문대학"))
        self.comboBox.setItemText(4, _translate("MainWindow", "자연과학대학"))
        self.comboBox.setItemText(5, _translate("MainWindow", "도시과학대학"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "과목검색"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">수강신청내역</span></p></body></html>"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">수강신청</span></p></body></html>"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "11"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "월"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "화"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "수"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "목"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "금"))
        self.label_49.setText(_translate("MainWindow", "*은 필수입력항목입니다"))


if __name__ == "__main__":
    import sys
    
    """
    url='https://wise.uos.ac.kr/uosdoc/api.ApiUcrMjTimeInq.oapi?'
    apiKey='202006623GWT62609'
    year='2020'
    term='A10'
    deptDiv='20000'
    dept='A200110111'
    subDept='A200200120'
    
    queryParams='apiKey='+apiKey+'&year='+year+'&term='+term+'&deptDiv='+deptDiv+'&dept='+dept+'&subDept='+subDept
    

    url=url+queryParams
    req=requests.get(url)
    html=req.text
    soup=BeautifulSoup(req.content,'html.parser')
    datas=soup.find_all('subject_nm')
    print(soup)
    for data in datas:
        print(data.text)
    """

    """
    url_2='https://wise.uos.ac.kr/uosdoc/api.ApiApiDeptList.oapi?'
    apiKey='202006623GWT62609'

    queryParams2='apiKey='+apiKey
    url2=url_2+queryParams2

    req = requests.get(url2) 
    html = req.text 

    soup2=BeautifulSoup(req.content,'html.parser')
    print(soup2)
    """
   
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle(QtWidgets.QStyleFactory.create('Fusion'))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
